# Generated by Django 4.2.5 on 2023-10-04 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active_Sessions',
            new_name='Active_Session',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address_verified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='identity_verified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('tAcsp', 'Trust and Company Service Providers'), ('fiAc', 'Financial Institutions and Casinos'), ('lAc', 'Lawyers and Conveyancing'), ('accountants', 'Accountants'), ('rea', 'Real Estate Agents'), ('hvd', 'High Value Dealers'), ('tab', 'TAB New Zealand'), ('vasp', 'Virtual Asset Service Provider')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
