# Generated by Django 4.0.6 on 2023-10-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_active_sessions_active_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('tAcsp', 'Trust or Company Service Provider'), ('fiAc', 'Financial Institutions or Casino'), ('lAc', 'Lawyer or Conveyancer'), (
                'accountants', 'Accountant'), ('rea', 'Real Estate Agent'), ('hvd', 'High Value Dealer'), ('tab', 'TAB New Zealand'), ('vasp', 'Virtual Asset Service Provider')], max_length=20),
        ),

    ]
