# Generated by Django 4.0.6 on 2023-11-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_customer_additional_info_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_registration_num',
            field=models.BigIntegerField(unique=True),
        ),
    ]
