# Generated by Django 4.0.6 on 2023-10-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
