# Generated by Django 4.0.6 on 2023-11-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_company_company_registration_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.company'),
        ),
        migrations.AlterField(
            model_name='director',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.customer'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.customer'),
        ),
    ]
