# Generated by Django 4.0.6 on 2023-10-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/address/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='proof_of_identity',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/identity/'),
        ),
    ]
