# Generated by Django 4.0.6 on 2023-10-11 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_initial_entity(apps, schema_editor):
    Entity = apps.get_model('base_app', 'Entity')
    Entity.objects.create(id=1, name='Base Entity')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0007_customer_proof_of_address_customer_proof_of_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_initial_entity),
        migrations.AddField(
            model_name='active_session',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareholder',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entity',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base_app.entity'),
            preserve_default=False,
        ),
    ]
