# Generated by Django 4.0.6 on 2023-10-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_entity_active_session_entity_company_entity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('name',), 'verbose_name_plural': 'Registered Entities'},
        ),
    ]
