# Generated by Django 4.0.6 on 2023-10-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_entity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_session',
            old_name='url',
            new_name='open_app',
        ),
    ]
