# Generated by Django 4.0.6 on 2023-10-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_alter_available_apps_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Available_Apps',
            new_name='AvailableApps',
        ),
    ]
