# Generated by Django 4.0.6 on 2023-10-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_rename_available_apps_availableapps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active_Session',
        ),
    ]
