# Generated by Django 4.0.6 on 2023-10-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableapps',
            name='display_name',
            field=models.CharField(default='form', max_length=100),
            preserve_default=False,
        ),
    ]
