# Generated by Django 4.0.6 on 2023-11-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_customuser'),
        ('base_app', '0016_availableapps_display_name'),
    ]

    operations = [
    ]
