# Generated by Django 4.0.6 on 2023-11-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('offer_anonymity', models.CharField(max_length=20)),
                ('offer_large_value_services', models.CharField(max_length=20)),
                ('offer_services_black_list', models.CharField(max_length=20)),
                ('offer_services_grey_list', models.CharField(max_length=20)),
                ('offer_services_outside_NZ', models.CharField(max_length=20)),
                ('cash_intensive', models.CharField(max_length=20)),
                ('company_services', models.CharField(max_length=20)),
                ('trust_services', models.CharField(max_length=20)),
                ('remittance_services', models.CharField(max_length=20)),
                ('virtual_assets_services', models.CharField(max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.entity')),
            ],
        ),
    ]
